### ISSUE TITLE
🪄 Enhancement - Better sanity checks for non-existing env variables

### ISSUE THREAD

**Issue by dustin-brisebois** [pysnippet/fastapi-oauth2#30]
### Summary

Add sanity checks for .env not setup / configured - as is it defaults to a NoneType error if the .env values don't exist.

**Comment by ArtyomVancyan** [comment]
@dustin-brisebois, it is not necessary to load config from environment variables (e.g. it can be loaded from various types of files such as YAML, JSON, XML, etc.) and apart from that, the `.env` file is used only in the demo app which is a sample application for testing and stuff (you can use it as a template for your application and implement the above described for it). So, I do not see a need for this for now. Thank you for your interest in the project :)
