### ISSUE TITLE
🐛 redirect_url ignored

### ISSUE THREAD

**Issue by twsl** [pysnippet/fastapi-oauth2#51]
### Bug description

OAuth2Core doesnt use redirect_uri
https://github.com/pysnippet/fastapi-oauth2/blob/33b42dcebc098c0a1086880bd76ff8c110bb0da2/src/fastapi_oauth2/core.py#L79-L80

despite passing it in `__init__`
https://github.com/pysnippet/fastapi-oauth2/blob/33b42dcebc098c0a1086880bd76ff8c110bb0da2/src/fastapi_oauth2/core.py#L69

So i'd propose
```suggestion
return self.redirect_uri if self.redirect_uri else urljoin(str(request.base_url), "/oauth2/%s/token" % self.provider)
```

### Reproduction steps

Set a different redirect uri cause you overwrote the default oauth2_router, wonder why the redirect uri is ignored

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Firefox

### OS

Linux

**Comment by ArtyomVancyan** [comment]
@twsl, thanks for the report, but what you described above is a misunderstanding. The `redirenct_uri` of the [OAuth2Client](https://docs.pysnippet.org/fastapi-oauth2/integration/configuration#oauth2client) refers to a specific path where the user should be redirected when the authentication process is done (e.g., `https://example.com/dashboard` see the [docs](https://docs.pysnippet.org/fastapi-oauth2/integration/configuration)), if it isn't provided it redirects to the `base_uri` of your FastAPI application which is usually the `/` path. Meanwhile, the `get_redirect_uri` refers to the OpenID Connect token endpoint handler URL managed by [fastapi-oauth2](https://github.com/pysnippet/fastapi-oauth2) itself.

Please feel free to ask questions about the project and configuration if you need help. For questions, please use [discussions](https://github.com/pysnippet/fastapi-oauth2/discussions) section of the repository in the future :)

P.S. Sorry for not getting back to you sooner.
